Add JavaQueryParticipantTest.java to the set of excluded tests, since they fail consistently in AbstractGWTPluginTestCase setup.
Since disabling this test, I've had 3 successful runs of the tests, after
seeing this fail a half dozen times in a row. But looking at the code it is
hard to see why this fails more reliably than some other tests.

Here is the relevant stack trace:
JavaQueryParticipantTest.testParamTypeSearch()
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException)
at org.eclipse.swt.SWT.error(SWT.java:4441)
at org.eclipse.swt.SWT.error(SWT.java:4356)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3774)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3412)
at com.google.gdt.eclipse.core.SWTUtilities.delay(SWTUtilities.java:130)
at com.google.gdt.eclipse.core.jobs.JobsUtilities.waitForIdle(JobsUtilities.java:37)
at com.google.gwt.eclipse.core.test.AbstractGWTPluginTestCase.createTestProject(AbstractGWTPluginTestCase.java:275)
at com.google.gwt.eclipse.core.test.AbstractGWTPluginTestCase.setUp(AbstractGWTPluginTestCase.java:229)
at junit.framework.TestCase.runBare(TestCase.java:139)
Caused by: java.lang.NullPointerException: null
at org.eclipse.ui.internal.WorkbenchPage.setPerspective(WorkbenchPage.java:4061)
at org.eclipse.ui.internal.WorkbenchWindow.setup(WorkbenchWindow.java:733)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:888)
at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:120)
at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:85)
at org.eclipse.e4.core.contexts.ContextInjectionFactory.inject(ContextInjectionFactory.java:73)
at org.eclipse.ui.internal.Workbench.createWorkbenchWindow(Workbench.java:1480)
at org.eclipse.ui.internal.Workbench.getActiveWorkbenchWindow(Workbench.java:1453)
at com.google.gdt.eclipse.suite.GdtPlugin.maybeAddNewWizardActionsToWorkbench(GdtPlugin.java:317)
at com.google.gdt.eclipse.suite.GdtPlugin.access$3(GdtPlugin.java:313)
at com.google.gdt.eclipse.suite.GdtPlugin$4.run(GdtPlugin.java:343)
at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3774)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3412)
at com.google.gdt.eclipse.core.SWTUtilities.delay(SWTUtilities.java:130)
at com.google.gdt.eclipse.core.jobs.JobsUtilities.waitForIdle(JobsUtilities.java:37)
at com.google.gwt.eclipse.core.test.AbstractGWTPluginTestCase.createTestProject(AbstractGWTPluginTestCase.java:275)
at com.google.gwt.eclipse.core.test.AbstractGWTPluginTestCase.setUp(AbstractGWTPluginTestCase.java:229)
at junit.framework.TestCase.runBare(TestCase.java:139)

It looks like the root cause is that the GdtPlugin needs to be activated
to acomplish some setup, but it is doing a lot of asynchronous things
that are likely problematic on their own but are breaking badly in tests.
-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=86311586